# This file was generated by GoReleaser. DO NOT EDIT.
cask "bndry" do
  name "bndry"
  desc "Friendly CLI wrapper for HashiCorp Boundary focused on SSH workflows"
  homepage "https://github.com/ofkm/bndry"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bndry"

  on_macos do
    on_intel do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Darwin_x86_64.tar.gz"
      sha256 "e69bf8b8f54e4e17c7740342f35bb05f2f75c0978fc6658f5d01f52635b76706"
    end
    on_arm do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Darwin_arm64.tar.gz"
      sha256 "8d9e37ca0790d31d19fc24d7222eb6f19207bfe7e5159431adae4700cf105fda"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Linux_x86_64.tar.gz"
      sha256 "8f6beb7b414c895219b26464aef68cd1a21efbbdd01c7504dc73784e66f6aa3c"
    end
    on_arm do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Linux_arm64.tar.gz"
      sha256 "1151976a1a6e118ceaea85253a95a1cd31d45afb1da155ff2c7c07e4ad6549da"
    end
  end

  # No zap stanza required
end
