# This file was generated by GoReleaser. DO NOT EDIT.
cask "bndry" do
  name "bndry"
  desc "Friendly CLI wrapper for HashiCorp Boundary focused on SSH workflows"
  homepage "https://github.com/ofkm/bndry"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bndry"

  on_macos do
    on_intel do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Darwin_x86_64.tar.gz"
      sha256 "c7d5ee06808afd68f7c862eee54301a0aa1561afbad331483b86e0d7334f5c00"
    end
    on_arm do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Darwin_arm64.tar.gz"
      sha256 "7a10188eb100ab65e86b635f209054174015ea00c8972689412dc5694466f447"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Linux_x86_64.tar.gz"
      sha256 "f727cd811077ed8359654b7df2264a9bc7c480b4dec9aee198e806b976e50afe"
    end
    on_arm do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Linux_arm64.tar.gz"
      sha256 "bbd5cd9d0f8de4f59c8992e56ba71d6431b149471035c3752a2f1ab7df914979"
    end
  end

  # No zap stanza required
end
