# This file was generated by GoReleaser. DO NOT EDIT.
cask "bndry" do
  name "bndry"
  desc "Friendly CLI wrapper for HashiCorp Boundary focused on SSH workflows"
  homepage "https://github.com/ofkm/bndry"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bndry"

  on_macos do
    on_intel do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Darwin_x86_64.tar.gz"
      sha256 "15bb26cecabfa07415bd4071b7ec282ff5716704570241cb69e77937b900b2ff"
    end
    on_arm do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Darwin_arm64.tar.gz"
      sha256 "e9dcbd38e6d5317b09e5d38a201dcfa4fc6b1d2d88231f34883f9ff263370fea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Linux_x86_64.tar.gz"
      sha256 "e047648149cccfb8d45b8c19fa3b4e44342245b2bcd1bbe3231b7dd077d43b74"
    end
    on_arm do
      url "https://github.com/ofkm/bndry/releases/download/v#{version}/bndry_Linux_arm64.tar.gz"
      sha256 "c2e28d31a348ffe48ad67e4f4b9d7873b072c6193292fd728df869adb2110e8e"
    end
  end

  # No zap stanza required
end
