# This file was generated by GoReleaser. DO NOT EDIT.
cask "ofkm-tools" do
  name "ofkm-tools"
  desc "OFKM developer utilities"
  homepage "https://github.com/ofkm/ofkm-tools"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ofkm-tools"

  on_macos do
    on_intel do
      url "https://github.com/ofkm/ofkm-tools/releases/download/v#{version}/ofkm-tools_Darwin_x86_64.tar.gz"
      sha256 "21ce93c62c8a682650f4487da43b5450c6cfb9a30442d2667b53ca9ed2a817b2"
    end
    on_arm do
      url "https://github.com/ofkm/ofkm-tools/releases/download/v#{version}/ofkm-tools_Darwin_arm64.tar.gz"
      sha256 "2f44a458f847f6b4188cc1f4cf10342f6914823c28cb4f19d0cb4b3c441a0655"
    end
  end

  # No zap stanza required
end
