# This file was generated by GoReleaser. DO NOT EDIT.
cask "tally" do
  version "0.4.0"

  on_macos do
    sha256 "a04ebb9fd94bdaefcb251d70f1671f44470e15c91ddbcee9fba8ade3987c6f32"
    url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "94ba45d264332937788ffb324cedadf4ed3b1e4a20b3be6b78b5955c72ffc2bd"
      url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1f1db8334aa85d70df7257722bf67e9cb7357893308ff0173295f1fc03e1b0d7"
      url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "tally"
  desc "A modern Rust source line counter inspired by cloc."
  homepage "https://github.com/ofkm/tally"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tally"

  # No zap stanza required

end
