# This file was generated by GoReleaser. DO NOT EDIT.
cask "tally" do
  version "0.3.0"

  on_macos do
    sha256 "0fc56a1699ed6330ef76ac60bbf45b75638cb5845ddde464d91868c004bdc656"
    url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "4a6c40da11224b2c08da8ef9be4a824f19106b0ee2930f06db661619741f14c1"
      url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bc2401ac5b5d5f520df27fc014d5de3f1e4ca64b60905d9681aa0acb91cf8f6b"
      url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "tally"
  desc "A modern Rust source line counter inspired by cloc."
  homepage "https://github.com/ofkm/tally"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tally"

  # No zap stanza required

end
