# This file was generated by GoReleaser. DO NOT EDIT.
cask "tally" do
  version "0.2.0"

  on_macos do
    sha256 "2be470a3957b0acd4e08f50b102b33a5274fd3d6ce4e04885f836a9504c5dd98"
    url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "1869b09b9e0391cb95b4a1e73ed1bc238eb9afaf24ac0e7f71f4e627e3f41740"
      url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "05379070dcb755d5cf8573ac66350c90c9300c194420b1c616b23a08d9af218d"
      url "https://github.com/ofkm/tally/releases/download/v#{version}/tally_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "tally"
  desc "A modern Rust source line counter inspired by cloc."
  homepage "https://github.com/ofkm/tally"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tally"

  # No zap stanza required

end
